spring:
  mvc:
    view:
      suffix: .html

  redis:
    jedis:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 10
        max-wait: 10000
    host: 127.0.0.1
    password: 123456
    port: 6379
