server:
  port: 8081

spring:
  jmx:
    enabled: false
  application:
    name: gateway
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: true
      routes:
        - id: after_route
          uri: https://www.baidu.com
          predicates:
            - Path=/s
            - Query=wd,.+
      enabled: true
logging:
  level:
    root: info
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"