#redisUtil配置
redisUtil:
  host: 127.0.0.1          # 地址
  database: 0          # 数据库
  password: lf0507          # 密码
  timeout: 500          # 超时时间
  port: 6379          # 端口
  max-active: 100  # 给定时间内连接池可以分配的最大连接数
  max-idle: 20
  min-idle: 10